### ISSUE TITLE
Can we obatin the imagenet1k buffer (pretrained on in1k with convd4)

### ISSUE THREAD

**Issue by williamium3000** [justincui03/tesla#2]
Hi.
Thanks for the great work.
I am wondering if you can open-source the buffer for in1k. It's too computationally intensive to train 50 models on the imagenet1k dataset.

Best
Yijiang

**Comment by yfpeng1234** [comment]
Hi, I follow the command line in README to generate buffer trajectory for cifar10. It could not converge, do you encounter this problem?

**Comment by justincui03** [comment]
Hi, Yijiang,

Yes, we released a set of pretrained ConvNetD4 models [here](https://github.com/justincui03/tesla?tab=readme-ov-file#generating-expert-trajectories)
